# this gives a name to the actual github action
name: Deploy Silo Watch

# this tells us we can trigger it two ways
# making a code push to the main branch
# manually from the actions tab on github
on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows you to manually trigger this deployment from the GitHub Actions tab

# gives the envirment variables.
# alows for easy updates 
env:
  PROJECT_ID: "project-7f6ebc51-8bd3-4490-bdd" 
  REGION: "us-central1"
  SERVICE_NAME: "silo-watch"

# this spins up a (as requested) ubuntu image thats only function is to get all my code over to GCP then it imeditatly self destructs
# it is only given read access to the github repo
# the write access is just a prep for gcp "runner" coming up below 
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    # this is the list in order that the gcp runner preforms
    steps:
      #step 1
      #the name portion is just a placeholder for the github actions so a human can read and understand
      #we are grabbing the code from the github repo and handing it to the gcp runner the @v4 is the version number (could change)
      - name: Checkout Code
        uses: actions/checkout@v4

      # step 2
      # this makes sure the runner has all the required tools it will need to prefom the unit tests
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      # step 3
      # this looks for any files starting with test_ 
      # this runs unit tests to make sure all of the application logic still working before deployment
      - name: Unit Tests (pytest)
        run: |
          pytest

        # step 4
        # added a linter inside of pipeline first it gets installed then it gets ran
      - name: Linter (flake8)
        run: |
          flake8

      # step 5
      # allows the gcp runner to actually gain access in this case though the workload identiy federation, a type of passwordless handshake
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/902081503325/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-deployer@project-7f6ebc51-8bd3-4490-bdd.iam.gserviceaccount.com'

      # step 6
      # installs the google cloud command line tool onto the runner
      # this is used to actually deploy the app down in step 8
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # step 7
      # this istalls the terraform command line tools onto the runner to actually run the terraform from in the next step (5)
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # step 7
      # this inatializes terraform and it goes into the main.tf file to go see what "plugin" we need
      # in this case its gcp but it could be others like aws or azure
      # this actually starts to "apply" the instructions written in the main.tf
      # it is auto approved because there is no one there to interact with 
      # init=wake up and go see and grab the needed plugin
      # apply=now provision the gcp cloud run service from the main.tf instructions
      # -the building meeting the specifications is built but no machines placed inside it yet
      - name: Terraform Init & Apply
        run: |
          terraform init
          terraform apply -auto-approve

      # step 8
      # this takes the newly built gcp container and builds my actual python (or whatever type program) in/on it.
      # then it actually ships it off to the cloud run service aka deploys 
      # 1 grabs the name of the application from the top of the file (silo-watch)
      # 2 grabs all of the files in the current dir (/app) refrences the dockerfile and builds the container
      # 3 grabs the region from the top of the file
      # 4 grabs the project id from the top of the file
      # 5 asking it to just run with out giving any prompts
      - name: Build and Deploy Application Code
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --source . \
            --region ${{ env.REGION }} \
            --project ${{ env.PROJECT_ID }} \
            --quiet 